sudo: required
langauge: generic
services:
    - docker
before_install:
    # we're going to build a test version of the client project here to run tests with images made out of the Dockerfile.dev files
    - docker build -t agedi/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true agedi/react-test npm run test

after_success:
    - docker build -t agedi/multi-client ./client
    - docker build -t agedi/multi-server ./server
    - docker build -t agedi/multi-nginx ./nginx
    - docker build -t agedi/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push agedi/multi-client
    - docker push agedi/multi-server
    - docker push agedi/multi-nginx
    - docker push agedi/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-067635769092
    bucket_path: docker-multi
    on: # only deploy on branch master
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY